# -*- coding: utf-8 -*-
"""Central UI registry for pages, actions, tables and barcode print profiles."""

from .ui_manifest import (
    WorkspaceActionSpec,
    WorkspaceBarcodeProfileSpec,
    WorkspaceManifest,
    WorkspaceMenuEntrySpec,
    WorkspaceMenuSpec,
    WorkspaceTableSpec,
    ACTION_SPECS,
    UTILITY_ACTION_KEYS,
    PAGE_MANIFESTS,
    BARCODE_PRINT_PROFILES,
    MAIN_NAVIGATION_MENUS,
    page_manifest,
    page_factory_ids,
    page_meta_keys,
    page_navigation_groups,
    should_show_action_bar,
    action_spec,
    action_keys_for_page,
    effective_action_keys_for_page,
    action_specs_for_page,
    table_ids_for_page,
    barcode_profile_spec,
    barcode_profile_ids,
    barcode_profile_settings_prefixes,
    navigation_menus,
)

__all__ = [
    "WorkspaceActionSpec",
    "WorkspaceBarcodeProfileSpec",
    "WorkspaceManifest",
    "WorkspaceMenuEntrySpec",
    "WorkspaceMenuSpec",
    "WorkspaceTableSpec",
    "ACTION_SPECS",
    "UTILITY_ACTION_KEYS",
    "PAGE_MANIFESTS",
    "BARCODE_PRINT_PROFILES",
    "MAIN_NAVIGATION_MENUS",
    "page_manifest",
    "page_factory_ids",
    "page_meta_keys",
    "page_navigation_groups",
    "should_show_action_bar",
    "action_spec",
    "action_keys_for_page",
    "effective_action_keys_for_page",
    "action_specs_for_page",
    "table_ids_for_page",
    "barcode_profile_spec",
    "barcode_profile_ids",
    "barcode_profile_settings_prefixes",
    "navigation_menus",
]
