# -*- coding: utf-8 -*-
from database.repositories.cashbox_repo import CashboxRepository
class CashboxDAO:
    def __init__(self): self.repo=CashboxRepository()
    def bootstrap_defaults(self): return self.repo.bootstrap_defaults()
    def get_cashboxes(self, include_archived=False): return self.repo.list_cashboxes(include_archived)
    def get_bank_accounts(self, include_archived=False): return self.repo.list_bank_accounts(include_archived)
    def get_cashbox(self, cid): return self.repo.get_cashbox(cid)
    def get_bank_account(self, bid): return self.repo.get_bank_account(bid)
    def add_cashbox(self, data): return self.repo.add_cashbox(data)
    def update_cashbox(self, cid, data): return self.repo.update_cashbox(cid,data)
    def archive_cashbox(self, cid): return self.repo.archive_cashbox(cid)
    def add_bank_account(self, data): return self.repo.add_bank_account(data)
    def update_bank_account(self, bid, data): return self.repo.update_bank_account(bid,data)
    def archive_bank_account(self, bid): return self.repo.archive_bank_account(bid)
    def default_cashbox_id(self, branch_id=None): return self.repo.default_cashbox_id(branch_id)
    def record_movement(self, data): return self.repo.record_movement(data)
    def movements(self, limit=200, cashbox_id=None, bank_account_id=None): return self.repo.movements(limit,cashbox_id,bank_account_id)
    def delete_reference_movements(self, reference_type, reference_id): return self.repo.delete_reference_movements(reference_type,reference_id)
    def current_open_shift(self, cashbox_id=None): return self.repo.current_open_shift(cashbox_id)
    def shifts(self, limit=100, status=None): return self.repo.shifts(limit,status)
    def open_shift(self, data): return self.repo.open_shift(data)
    def shift_summary(self, shift_id): return self.repo.shift_summary(shift_id)
    def close_shift(self, shift_id, actual_amount, notes=''): return self.repo.close_shift(shift_id,actual_amount,notes)
cashbox_dao=CashboxDAO()
