# -*- coding: utf-8 -*-
from .settings_document_tabs import (
    BranchesSettingsTab,
    CategoriesSettingsTab,
    FinanceSettingsTab,
    ManufacturingSettingsTab,
    MaterialsSettingsTab,
    PartiesSettingsTab,
    PosSettingsTab,
    ReportsSettingsTab,
    AccountingSettingsTab,
    CompanySettingsTab,
    InventorySettingsTab,
    PrintingSettingsTab,
    RestaurantSettingsTab,
    SecuritySettingsTab,
    SETTINGS_SECTION_TABS,
    TransactionsSettingsTab,
    UsersSettingsTab,
    SettingsSectionDocumentTab,
    UISettingsTab,
)

__all__ = [
    'BranchesSettingsTab',
    'CategoriesSettingsTab',
    'FinanceSettingsTab',
    'ManufacturingSettingsTab',
    'MaterialsSettingsTab',
    'PartiesSettingsTab',
    'PosSettingsTab',
    'ReportsSettingsTab',
    'AccountingSettingsTab',
    'CompanySettingsTab',
    'InventorySettingsTab',
    'PrintingSettingsTab',
    'RestaurantSettingsTab',
    'SecuritySettingsTab',
    'SETTINGS_SECTION_TABS',
    'TransactionsSettingsTab',
    'UsersSettingsTab',
    'SettingsSectionDocumentTab',
    'UISettingsTab',
]
