# -*- coding: utf-8 -*-
"""Central Al Rajhi design tokens.

This module is the single source of truth for product colors, semantic tones,
spacing and corner radii.  UI code should read from ThemeManager/DesignSystem,
not duplicate literal colors in new widgets.
"""
from __future__ import annotations

BRAND = {
    'app_name_ar': 'الراجحي للمحاسبة والمستودعات والتصنيع',
    'login_name_ar': 'الراجحي للمحاسبة',
    'developer_card_name_ar': 'الراجحي للمحاسبة والمستودعات والتصنيع',
    'font_family': "'Tajawal', 'Segoe UI', sans-serif",
    'radius_sm': 8,
    'radius_md': 12,
    'radius_lg': 18,
    'spacing_xs': 4,
    'spacing_sm': 8,
    'spacing_md': 14,
    'spacing_lg': 24,
    # Phase 332: central typography and shell metrics.  New widgets should
    # consume these values instead of introducing local font-size/height
    # constants.  Values are intentionally conservative so the UI becomes
    # readable without breaking dense accounting workflows.
    'font_size_body_pt': 11,
    'font_size_table_pt': 10,
    'font_size_caption_px': 11,
    'font_size_value_px': 13,
    'font_size_title_px': 20,
    'font_size_hero_px': 25,
    'nav_height': 74,
    'nav_icon_size': 26,
    'nav_button_min_width': 76,
    'nav_button_max_width': 112,
    'nav_button_home_width': 64,
    'nav_button_height': 64,
    'nav_font_px': 12,
    'action_bar_height': 52,
    'action_button_icon': 18,
    'action_button_font_px': 12,
    'action_button_min_height': 38,
    'table_header_padding': 10,
    'table_cell_padding': 7,
    'input_min_height': 34,
    # Phase349: invoice-like footer/action sizing and editable-cell focus.
    'transaction_footer_font_px': 13,
    'transaction_footer_value_font_px': 14,
    'transaction_footer_action_font_px': 14,
    'transaction_footer_action_min_height': 46,
    # Phase352: logo-inspired identity metrics for shell chrome and first-run screens.
    'brand_phase': 368,
    'brand_logo_path': 'alrajhi_client/assets/brand/logo.png',
    'brand_logo_large_px': 118,
    'brand_logo_login_px': 96,
    'brand_logo_login_header_px': 64,
    'splash_width': 660,
    'splash_height': 430,
    'login_card_width': 520,
    'login_pre352_safe_width': 500,
    'login_pre352_safe_height': 660,
    'login_pre352_min_width': 430,
    'login_pre352_min_height': 600,
    'login_stable_width': 680,
    'login_stable_height': 635,
    'login_form_max_width': 560,
    'activation_card_width': 540,
    'brand_tab_min_height': 38,
    'brand_tab_padding_x': 18,
    'brand_dialog_header_height': 58,
    'dialog_min_width': 560,
    'dialog_min_height': 360,
    'dialog_action_min_height': 42,
    'dialog_action_min_width': 104,
    'dialog_primary_min_width': 126,
    'message_box_min_width': 460,
    'toast_min_width': 360,
    'toast_max_width': 560,
    'brand_button_min_height': 42,
    # Phase354: branded shell/tab/menu/action runtime metrics.
    'shell_tab_main_badge_width': 58,
    'shell_tab_sub_badge_width': 54,
    'shell_tab_active_min_width': 150,
    'shell_action_context_min_width': 180,
    'shell_action_primary_min_width': 112,
    'shell_menu_button_radius': 16,
    # Phase353: first-run branded runtime layout.
    'first_run_panel_width': 330,
    'first_run_form_width': 520,
    'first_run_primary_button_height': 48,
    'first_run_secondary_button_height': 44,
    'first_run_chip_height': 30,
    'first_run_device_panel_height': 92,
    # Phase361/362/363/364: expanded vertical login layout and non-overlapping login sections.
    # Phase364 reserves a dedicated password-row container and an explicit
    # spacer widget, instead of relying on stylesheet margins that can still
    # paint under the remember/language panel in some Qt styles.
    'login_rtl_expanded_width': 980,
    'login_rtl_expanded_height': 945,
    'login_rtl_min_width': 940,
    'login_rtl_min_height': 900,
    'login_form_expanded_width': 580,
    'login_form_expanded_min_height': 870,
    'login_credentials_min_height': 356,
    'login_password_row_height': 68,
    'login_password_options_spacer_height': 46,
    'login_options_min_height': 150,
    'login_action_button_height': 54,
    'login_secondary_button_height': 50,
    'login_field_height': 52,
    'login_vertical_section_spacing': 22,
    'login_section_gap': 38,
    'login_password_bottom_gap': 18,
    # Phase355: branded tables and transaction footer metrics.
    'brand_table_row_height': 38,
    'brand_table_header_min_height': 42,
    'brand_table_current_border_px': 2,
    'brand_table_current_radius': 6,
    'transaction_footer_panel_min_height': 88,
    'transaction_footer_summary_min_height': 74,
    'transaction_footer_button_min_width': 126,
    'transaction_footer_button_spacing': 12,
    # Phase401: Basit-inspired operational sizing.
    'basit_pos_card_height': 64,
    'basit_pos_card_min_width': 150,
    'basit_category_card_height': 58,
    'basit_invoice_row_height': 36,
    'basit_total_height': 58,
    'basit_toolbar_height': 46,
    'basit_dashboard_card_height': 96,
    # Phase406: Basit shell chrome metrics.
    'basit_shell_nav_height': 70,
    'basit_shell_action_height': 50,
    'basit_shell_tab_height': 36,
    'basit_shell_menu_button_radius': 4,
    'basit_dialog_min_width': 560,
    'basit_dialog_header_height': 54,
    'basit_dialog_button_height': 44,
    'basit_startup_card_radius': 8,
}



# Product palette extracted into stable design tokens.
# Phase352: colors are aligned with the bundled logo: deep ink/navy, blue-teal
# progression, and restrained gold/sand accents for a professional ERP identity.
ALRAJHI_INK = '#071A2E'
ALRAJHI_NAVY = '#083A63'
ALRAJHI_BLUE = '#0A6D9A'
ALRAJHI_BLUE_2 = '#0B83B7'
ALRAJHI_TEAL = '#087D78'
ALRAJHI_ACCENT = '#0AA7A7'
ALRAJHI_GOLD = '#C99A2E'
ALRAJHI_SAND = '#F3E8CF'
# Phase401: Basit-inspired operational palette.  These tokens deliberately
# mirror the visual language users recognize from Al-Basit: strong blue
# command cards, yellow active strips, red/orange totals, and a quiet grey
# accounting canvas.
BASIT_BLUE = '#0076D7'
BASIT_BLUE_HOVER = '#005EAE'
BASIT_YELLOW = '#F2D21B'
BASIT_YELLOW_SOFT = '#FFF3A3'
BASIT_RED = '#D93600'
BASIT_RED_DARK = '#B92E00'
BASIT_GREY = '#EEF1F6'
BASIT_GRID = '#F8FAFD'
BASIT_GRID_ALT = '#EEF3FA'
BRAND_GRADIENT_START = ALRAJHI_INK
BRAND_GRADIENT_MID = ALRAJHI_NAVY
BRAND_GRADIENT_END = ALRAJHI_TEAL

LIGHT_TOKENS = {
    'bg_window': '#F5F7FA',
    'bg_panel': '#FFFFFF',
    'bg_sidebar': '#EEF3F8',
    'bg_table': '#FFFFFF',
    'bg_table_alt': '#F8FAFC',
    'text_primary': '#1A202C',
    'text_secondary': '#4A5568',
    'text_muted': '#718096',
    'border': '#E2E8F0',
    'border_focus': ALRAJHI_ACCENT,
    'primary': ALRAJHI_BLUE,
    'primary_hover': ALRAJHI_BLUE_2,
    'primary_2': ALRAJHI_BLUE_2,
    'accent': ALRAJHI_ACCENT,
    'success': '#1F9D55',
    'danger': '#D64545',
    'warning': '#D69E2E',
    'info': ALRAJHI_ACCENT,
    'header_bg': ALRAJHI_BLUE,
    'header_text': '#FFFFFF',
    'selection_bg': '#D9E9FF',
    'selection_text': '#0B2444',
    'current_cell_bg': '#FFF4CC',
    'current_cell_border': ALRAJHI_ACCENT,
    'card_bg': '#FFFFFF',
    'input_bg': '#FFFFFF',
    'success_soft': '#EAF8F0',
    'warning_soft': '#FFF8E5',
    'danger_soft': '#FDECEC',
    'info_soft': '#EAF3FF',
    'brand_soft': '#EAF1F8',
    'shadow': 'rgba(15,61,117,0.16)',
    # Phase352 brand identity layer.
    'brand_ink': ALRAJHI_INK,
    'brand_navy': ALRAJHI_NAVY,
    'brand_blue': ALRAJHI_BLUE,
    'brand_teal': ALRAJHI_TEAL,
    'brand_gold': ALRAJHI_GOLD,
    'brand_sand': ALRAJHI_SAND,
    'brand_on_dark': '#FFFFFF',
    'brand_gradient_start': BRAND_GRADIENT_START,
    'brand_gradient_mid': BRAND_GRADIENT_MID,
    'brand_gradient_end': BRAND_GRADIENT_END,
    'surface_root': '#F4F7F8',
    'surface_raised': '#FFFFFF',
    'surface_sunken': '#EEF5F4',
    'login_card_bg': '#FFFFFF',
    'activation_card_bg': '#FFFFFF',
    'brand_mark_bg': '#E8F7F6',
    'license_status_bg': '#EAF3FF',
    'input_focus_bg': '#F6FBFF',
    'menu_bg': '#FFFFFF',
    'menu_active_bg': ALRAJHI_NAVY,
    'menu_active_text': '#FFFFFF',
    'menu_border': '#D6E2E7',
    'action_bar_bg': '#FFFFFF',
    'action_primary_bg': ALRAJHI_BLUE,
    'action_secondary_bg': '#EAF3F5',
    'action_danger_bg': '#FDECEC',
    'tab_active_bg': ALRAJHI_NAVY,
    'tab_inactive_bg': '#EFF5F7',
    'tab_active_text': '#FFFFFF',
    'tab_inactive_text': '#34515F',
    'tab_close_hover_bg': '#D64545',
    'table_header_bg': ALRAJHI_NAVY,
    'table_header_text': '#FFFFFF',
    'dialog_bg': '#FFFFFF',
    'dialog_header_bg': '#EAF3F5',
    'dialog_footer_bg': '#F5F8FA',
    'dialog_button_bg': '#FFFFFF',
    'transaction_summary_bg': '#F8FBFC',
    'transaction_summary_value': ALRAJHI_BLUE,
    'transaction_action_bg': ALRAJHI_BLUE,
    'transaction_close_bg': '#F5F8FA',
    'splash_progress_bg': 'rgba(255,255,255,0.24)',
    'splash_progress_chunk': '#FFFFFF',
    # Phase354 branded shell chrome tokens.
    'shell_tab_main_badge_bg': ALRAJHI_GOLD,
    'shell_tab_sub_badge_bg': ALRAJHI_ACCENT,
    'shell_tab_badge_text': '#FFFFFF',
    'shell_tab_active_underline': ALRAJHI_GOLD,
    'shell_menu_hover_bg': '#EAF3F5',
    'shell_menu_open_bg': '#DCECEF',
    'shell_action_context_bg': '#EAF3F5',
    'shell_action_primary_bg': ALRAJHI_BLUE,
    'shell_action_secondary_bg': '#F2F7F8',
    'shell_action_utility_bg': '#F8FBFC',
    # Phase353 first-run branded runtime tokens.
    'first_run_panel_bg': BRAND_GRADIENT_START,
    'first_run_panel_text': '#FFFFFF',
    'first_run_panel_muted': 'rgba(255,255,255,0.76)',
    'first_run_form_bg': '#FFFFFF',
    'first_run_login_header_bg': '#F7FBFC',
    'first_run_card_border': '#D6E2E7',
    'first_run_chip_bg': 'rgba(255,255,255,0.16)',
    'first_run_chip_text': '#FFFFFF',
    'first_run_footer_text': 'rgba(255,255,255,0.58)',
    'first_run_primary_bg': ALRAJHI_BLUE,
    'first_run_secondary_bg': '#F8FBFC',
    'activation_device_bg': '#F6FBFF',
    # Phase355 branded table and transaction footer runtime tokens.
    'table_current_bg': '#FFF3C4',
    'table_current_border': ALRAJHI_GOLD,
    'table_current_text': '#071A2E',
    'table_focus_ring': ALRAJHI_ACCENT,
    'table_header_line': ALRAJHI_GOLD,
    'table_row_hover_bg': '#EDF7F8',
    'transaction_footer_surface': '#FFFFFF',
    'transaction_footer_summary_bg': '#F5FAFB',
    'transaction_footer_summary_border': '#CFE1E6',
    'transaction_footer_label': '#46616E',
    'transaction_footer_value': ALRAJHI_BLUE,
    'transaction_footer_primary_bg': ALRAJHI_BLUE,
    'transaction_footer_secondary_bg': '#EEF6F7',
    'transaction_footer_close_bg': '#F8FBFC',
    # Phase356 branded dialog/system-window tokens.
    'dialog_title_text': ALRAJHI_NAVY,
    'dialog_subtitle_text': '#46616E',
    'dialog_accent_line': ALRAJHI_GOLD,
    'dialog_primary_bg': ALRAJHI_BLUE,
    'dialog_secondary_bg': '#EEF6F7',
    'dialog_close_bg': '#F8FBFC',
    'dialog_warning_bg': '#FFF7DB',
    'dialog_danger_bg': '#FDECEC',
    'dialog_success_bg': '#EAF8F0',
    'dialog_overlay_bg': '#F4F7F8',
    'dialog_header_text': '#FFFFFF',
    'dialog_panel_border': '#CFE1E6',
    # Phase401 Basit-inspired visual system tokens.
    'basit_blue': BASIT_BLUE,
    'basit_blue_hover': BASIT_BLUE_HOVER,
    'basit_yellow': BASIT_YELLOW,
    'basit_yellow_soft': BASIT_YELLOW_SOFT,
    'basit_red': BASIT_RED,
    'basit_red_dark': BASIT_RED_DARK,
    'basit_canvas': BASIT_GREY,
    'basit_card_bg': BASIT_BLUE,
    'basit_card_text': '#FFFFFF',
    'basit_card_border': '#00599C',
    'basit_category_bg': BASIT_YELLOW,
    'basit_category_text': '#1F2937',
    'basit_table_bg': BASIT_GRID,
    'basit_table_alt': BASIT_GRID_ALT,
    'basit_table_header_bg': '#C9D2E3',
    'basit_table_header_text': '#101827',
    'basit_table_current_bg': BASIT_YELLOW_SOFT,
    'basit_total_bg': BASIT_RED,
    'basit_total_text': '#FFFFFF',
    'basit_toolbar_bg': '#DDE5F2',
    'basit_toolbar_border': '#AAB8CC',
    'basit_shell_bg': '#DDE5F2',
    'basit_shell_menu_bg': BASIT_BLUE,
    'basit_shell_menu_text': '#FFFFFF',
    'basit_shell_active_bg': BASIT_YELLOW,
    'basit_shell_active_text': '#111827',
    'toast_success_bg': '#EAF8F0',
    'toast_info_bg': '#EAF3FF',
    'toast_warning_bg': '#FFF8E5',
    'toast_error_bg': '#FDECEC',
    'toast_success_text': '#166534',
    'toast_info_text': ALRAJHI_BLUE,
    'toast_warning_text': '#92400E',
    'toast_error_text': '#991B1B',
}



DARK_TOKENS = {
    'bg_window': '#0B1623',
    'bg_panel': '#111F2E',
    'bg_sidebar': '#0D1A28',
    'bg_table': '#111F2E',
    'bg_table_alt': '#0D1A28',
    'text_primary': '#F7FAFC',
    'text_secondary': '#CBD5E1',
    'text_muted': '#94A3B8',
    'border': '#27405B',
    'border_focus': '#5FA8FF',
    'primary': '#5FA8FF',
    'primary_hover': '#2D7FF9',
    'primary_2': '#1E5AA8',
    'accent': '#74B6FF',
    'success': '#38B56B',
    'danger': '#F87171',
    'warning': '#F2C45A',
    'info': '#74B6FF',
    'header_bg': '#0F3D75',
    'header_text': '#FFFFFF',
    'selection_bg': '#1E5AA8',
    'selection_text': '#FFFFFF',
    'current_cell_bg': 'rgba(242,196,90,0.28)',
    'current_cell_border': '#F2C45A',
    'card_bg': '#101C2A',
    'input_bg': '#0E1A27',
    'success_soft': 'rgba(31,157,85,0.18)',
    'warning_soft': 'rgba(214,158,46,0.18)',
    'danger_soft': 'rgba(214,69,69,0.18)',
    'info_soft': 'rgba(45,127,249,0.18)',
    'brand_soft': 'rgba(45,127,249,0.15)',
    'shadow': 'rgba(0,0,0,0.42)',
    # Phase352 brand identity layer.
    'brand_ink': '#EAF6FF',
    'brand_navy': '#102C44',
    'brand_blue': '#4FB3E8',
    'brand_teal': '#41C7BD',
    'brand_gold': '#F0C15A',
    'brand_sand': '#2B2518',
    'brand_on_dark': '#FFFFFF',
    'brand_gradient_start': '#06111E',
    'brand_gradient_mid': '#102C44',
    'brand_gradient_end': '#075A5A',
    'surface_root': '#091524',
    'surface_raised': '#111F2E',
    'surface_sunken': '#0C1A29',
    'login_card_bg': '#111F2E',
    'activation_card_bg': '#111F2E',
    'brand_mark_bg': 'rgba(65,199,189,0.14)',
    'license_status_bg': 'rgba(79,179,232,0.14)',
    'input_focus_bg': '#102437',
    'menu_bg': '#111F2E',
    'menu_active_bg': '#0A6D9A',
    'menu_active_text': '#FFFFFF',
    'menu_border': '#27405B',
    'action_bar_bg': '#111F2E',
    'action_primary_bg': '#0A6D9A',
    'action_secondary_bg': '#102437',
    'action_danger_bg': 'rgba(248,113,113,0.16)',
    'tab_active_bg': '#0A6D9A',
    'tab_inactive_bg': '#102437',
    'tab_active_text': '#FFFFFF',
    'tab_inactive_text': '#CBD5E1',
    'tab_close_hover_bg': '#F87171',
    'table_header_bg': '#102C44',
    'table_header_text': '#FFFFFF',
    'dialog_bg': '#111F2E',
    'dialog_header_bg': '#102437',
    'dialog_footer_bg': '#0C1A29',
    'dialog_button_bg': '#111F2E',
    'transaction_summary_bg': '#102437',
    'transaction_summary_value': '#4FB3E8',
    'transaction_action_bg': '#0A6D9A',
    'transaction_close_bg': '#102437',
    'splash_progress_bg': 'rgba(255,255,255,0.18)',
    'splash_progress_chunk': '#FFFFFF',
    # Phase354 branded shell chrome tokens.
    'shell_tab_main_badge_bg': '#F0C15A',
    'shell_tab_sub_badge_bg': '#41C7BD',
    'shell_tab_badge_text': '#06111E',
    'shell_tab_active_underline': '#F0C15A',
    'shell_menu_hover_bg': '#102437',
    'shell_menu_open_bg': '#12324C',
    'shell_action_context_bg': '#102437',
    'shell_action_primary_bg': '#0A6D9A',
    'shell_action_secondary_bg': '#102437',
    'shell_action_utility_bg': '#0C1A29',
    # Phase353 first-run branded runtime tokens.
    'first_run_panel_bg': '#06111E',
    'first_run_panel_text': '#FFFFFF',
    'first_run_panel_muted': 'rgba(255,255,255,0.72)',
    'first_run_form_bg': '#111F2E',
    'first_run_login_header_bg': '#102B45',
    'first_run_card_border': '#27405B',
    'first_run_chip_bg': 'rgba(255,255,255,0.12)',
    'first_run_chip_text': '#FFFFFF',
    'first_run_footer_text': 'rgba(255,255,255,0.54)',
    'first_run_primary_bg': '#0A6D9A',
    'first_run_secondary_bg': '#102437',
    'activation_device_bg': '#102437',
    # Phase355 branded table and transaction footer runtime tokens.
    'table_current_bg': 'rgba(240,193,90,0.26)',
    'table_current_border': '#F0C15A',
    'table_current_text': '#FFFFFF',
    'table_focus_ring': '#41C7BD',
    'table_header_line': '#F0C15A',
    'table_row_hover_bg': '#12324C',
    'transaction_footer_surface': '#111F2E',
    'transaction_footer_summary_bg': '#102437',
    'transaction_footer_summary_border': '#27405B',
    'transaction_footer_label': '#CBD5E1',
    'transaction_footer_value': '#4FB3E8',
    'transaction_footer_primary_bg': '#0A6D9A',
    'transaction_footer_secondary_bg': '#102437',
    'transaction_footer_close_bg': '#0C1A29',
    # Phase356 branded dialog/system-window tokens.
    'dialog_title_text': '#EAF6FF',
    'dialog_subtitle_text': '#CBD5E1',
    'dialog_accent_line': '#F0C15A',
    'dialog_primary_bg': '#0A6D9A',
    'dialog_secondary_bg': '#102437',
    'dialog_close_bg': '#0C1A29',
    'dialog_warning_bg': 'rgba(240,193,90,0.18)',
    'dialog_danger_bg': 'rgba(248,113,113,0.16)',
    'dialog_success_bg': 'rgba(56,181,107,0.16)',
    'dialog_overlay_bg': '#091524',
    'dialog_header_text': '#FFFFFF',
    'dialog_panel_border': '#27405B',
    # Phase401 Basit-inspired dark tokens.
    'basit_blue': '#2B8CE6',
    'basit_blue_hover': '#4FA3FF',
    'basit_yellow': '#F0C419',
    'basit_yellow_soft': 'rgba(240,196,25,0.28)',
    'basit_red': '#E64A19',
    'basit_red_dark': '#FF7043',
    'basit_canvas': '#0D1624',
    'basit_card_bg': '#1268B3',
    'basit_card_text': '#FFFFFF',
    'basit_card_border': '#4FA3FF',
    'basit_category_bg': '#F0C419',
    'basit_category_text': '#111827',
    'basit_table_bg': '#111F2E',
    'basit_table_alt': '#0D1A28',
    'basit_table_header_bg': '#253A55',
    'basit_table_header_text': '#FFFFFF',
    'basit_table_current_bg': 'rgba(240,196,25,0.24)',
    'basit_total_bg': '#E64A19',
    'basit_total_text': '#FFFFFF',
    'basit_toolbar_bg': '#162940',
    'basit_toolbar_border': '#38516C',
    'basit_shell_bg': '#162940',
    'basit_shell_menu_bg': '#1268B3',
    'basit_shell_menu_text': '#FFFFFF',
    'basit_shell_active_bg': '#F0C419',
    'basit_shell_active_text': '#111827',
    'toast_success_bg': 'rgba(56,181,107,0.18)',
    'toast_info_bg': 'rgba(79,179,232,0.18)',
    'toast_warning_bg': 'rgba(240,193,90,0.18)',
    'toast_error_bg': 'rgba(248,113,113,0.18)',
    'toast_success_text': '#BBF7D0',
    'toast_info_text': '#BAE6FD',
    'toast_warning_text': '#FDE68A',
    'toast_error_text': '#FECACA',
}



def get_tokens(theme: str = 'light') -> dict:
    """Return a copy of tokens for the requested theme."""
    source = DARK_TOKENS if theme == 'dark' else LIGHT_TOKENS
    return dict(source)
