# -*- coding: utf-8 -*-
"""Unified money/number presentation policy for UI, reports, POS, restaurant, and printing.

This module is deliberately independent from PyQt and from ``currency.py`` so it
can be imported by tests, CI guards, PyInstaller bootstrap code, and lightweight
models without pulling a GUI runtime.  It formats already-resolved display
amounts; it does not perform exchange-rate conversion.  Conversion remains the
responsibility of CurrencyManager/service layers before values reach the UI.
"""
from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
import re
from typing import Any, Mapping


CURRENCY_SYMBOLS: dict[str, str] = {
    "USD": "$",
    "SAR": "﷼",
    "SYP": "ل.س",
    "EUR": "€",
    "GBP": "£",
    "AED": "د.إ",
    "QAR": "ر.ق",
    "KWD": "د.ك",
    "OMR": "ر.ع.",
}

ARABIC_DIGITS = str.maketrans("٠١٢٣٤٥٦٧٨٩۰۱۲۳۴۵۶۷۸۹", "01234567890123456789")
WESTERN_TO_ARABIC = str.maketrans("0123456789", "٠١٢٣٤٥٦٧٨٩")

MONEY_KEYS = {
    "amount", "price", "unit_price", "selling_price", "purchase_price", "cost", "unit_cost",
    "discount", "discount_amount", "tax", "tax_amount", "subtotal", "total", "line_total",
    "paid", "paid_amount", "remaining", "refund_amount", "balance", "debit", "credit",
    "value", "total_value", "expected", "actual", "diff", "difference_amount",
}
QUANTITY_KEYS = {
    "qty", "quantity", "base_qty", "available", "available_qty", "original_qty",
    "previous_qty", "returnable_qty", "planned_qty", "produced_qty", "consumed_qty",
}


def _settings_get(key: str, default: Any = None) -> Any:
    try:
        from core.services.settings_service import settings_service  # type: ignore
        return settings_service.get(key, default)
    except Exception:
        return default


def normalize_currency_code(value: Any = None, default: str = "SYP") -> str:
    text = str(value or default or "SYP").strip().upper()
    # Accept symbols passed by old widgets and map them to known codes.
    reverse = {v: k for k, v in CURRENCY_SYMBOLS.items()}
    return reverse.get(text, text or "SYP")


def currency_code_from_payload(payload: Mapping[str, Any] | None = None, default: str | None = None) -> str:
    payload = payload or {}
    for key in ("display_currency", "currency", "currency_code", "document_currency"):
        value = payload.get(key)
        if value not in (None, ""):
            return normalize_currency_code(value, default or "SYP")
    return normalize_currency_code(default or _settings_get("display_currency", "SYP"), "SYP")


def currency_symbol(currency_code: Any = None, settings: Mapping[str, Any] | None = None) -> str:
    settings = settings or {}
    code = normalize_currency_code(currency_code or settings.get("display_currency") or _settings_get("display_currency", "SYP"))
    if code == normalize_currency_code(settings.get("display_currency")) and settings.get("currency_symbol"):
        return str(settings.get("currency_symbol") or "")
    return CURRENCY_SYMBOLS.get(code, code)


def _int_setting(key: str, default: int) -> int:
    try:
        return int(_settings_get(key, default))
    except Exception:
        return default


def _bool_setting(key: str, default: bool = False) -> bool:
    value = _settings_get(key, str(default).lower())
    return str(value).strip().lower() in {"1", "true", "yes", "on", "y", "نعم"}


def decimal_value(value: Any, default: str = "0") -> Decimal:
    """Parse old/new numeric payloads into Decimal safely.

    Handles Decimal('...') strings, Arabic/Persian digits, currency symbols,
    thousands separators, trailing minus signs, and scientific notation residues
    such as ``1E-22-`` generated by legacy float arithmetic.
    """
    if isinstance(value, Decimal):
        return value
    if value is None or value == "":
        return Decimal(default)
    text = str(value).strip().translate(ARABIC_DIGITS)
    if not text:
        return Decimal(default)
    if text.startswith("Decimal('") and text.endswith("')"):
        text = text[9:-2]
    if text.startswith('Decimal("') and text.endswith('")'):
        text = text[9:-2]
    # Legacy formatting sometimes produced trailing negative scientific strings.
    if text.endswith("-") and not text.startswith("-"):
        text = "-" + text[:-1]
    # Remove known currency codes/symbols and whitespace while preserving numeric notation.
    for code, symbol in CURRENCY_SYMBOLS.items():
        text = text.replace(code, "").replace(code.lower(), "").replace(symbol, "")
    text = text.replace(" ", "").replace("\u00a0", "")
    # Drop grouping commas.  Decimal separator is always normalized to dot in the app.
    text = text.replace(",", "")
    # Keep only a conservative numeric/scientific subset.
    text = re.sub(r"[^0-9eE+\-.]", "", text)
    if text in {"", "+", "-", ".", "-.", "+."}:
        return Decimal(default)
    try:
        return Decimal(text)
    except (InvalidOperation, ValueError):
        return Decimal(default)


def _quantum(decimals: int) -> Decimal:
    return Decimal("1") if decimals <= 0 else Decimal("1").scaleb(-int(decimals))


def quantize_money(value: Any, decimals: int = 2) -> Decimal:
    q = _quantum(decimals)
    num = decimal_value(value)
    # Suppress tiny residues before and after quantization.
    if abs(num) < q / Decimal("2"):
        num = Decimal("0")
    num = num.quantize(q, rounding=ROUND_HALF_UP)
    if num == Decimal("-0").quantize(q) or num == 0:
        return Decimal("0").quantize(q)
    return num


def _apply_number_format(text: str, number_format: str) -> str:
    if str(number_format or "western").lower() == "arabic":
        return text.translate(WESTERN_TO_ARABIC)
    return text


def _abbreviate_number(num: Decimal, decimals: int = 1) -> str:
    sign = "-" if num < 0 else ""
    n = abs(num)
    for threshold, suffix in ((Decimal("1000000000"), "B"), (Decimal("1000000"), "M"), (Decimal("1000"), "K")):
        if n >= threshold:
            return f"{sign}{(n / threshold):,.{decimals}f}{suffix}"
    return f"{num:,.{max(decimals, 0)}f}"


@dataclass(frozen=True)
class MoneyDisplayPolicy:
    currency_code: str = "SYP"
    currency_symbol: str = "ل.س"
    decimals: int = 2
    number_format: str = "western"
    abbreviate_numbers: bool = False
    group: bool = True

    @classmethod
    def from_settings(cls, currency_code: Any = None, payload: Mapping[str, Any] | None = None) -> "MoneyDisplayPolicy":
        payload = payload or {}
        settings_currency = _settings_get("display_currency", "SYP")
        # An explicit document/caller currency must override the ambient
        # display_currency present in settings payloads.  Otherwise print/report
        # code can accidentally relabel SYP document amounts as USD.
        code = normalize_currency_code(currency_code, "SYP") if currency_code not in (None, "") else currency_code_from_payload(payload, default=settings_currency)
        try:
            decimals = int(payload.get("currency_decimals", _settings_get("currency_decimals", "2")))
        except Exception:
            decimals = 2
        return cls(
            currency_code=code,
            currency_symbol=currency_symbol(code, payload),
            decimals=decimals,
            number_format=str(payload.get("number_format", _settings_get("number_format", "western")) or "western"),
            abbreviate_numbers=str(payload.get("abbreviate_numbers", _settings_get("abbreviate_numbers", "false"))).lower() in {"1", "true", "yes", "on"},
            group=str(payload.get("number_grouping", _settings_get("number_grouping", "true"))).lower() not in {"0", "false", "no", "off"},
        )

    def with_currency(self, currency_code: Any = None) -> "MoneyDisplayPolicy":
        code = normalize_currency_code(currency_code or self.currency_code)
        return MoneyDisplayPolicy(
            currency_code=code,
            currency_symbol=currency_symbol(code),
            decimals=self.decimals,
            number_format=self.number_format,
            abbreviate_numbers=self.abbreviate_numbers,
            group=self.group,
        )

    def format_money(self, value: Any, *, currency_code: Any = None, decimals: int | None = None, include_symbol: bool = True) -> str:
        policy = self.with_currency(currency_code) if currency_code else self
        decs = self.decimals if decimals is None else int(decimals)
        amount = quantize_money(value, decs)
        if self.abbreviate_numbers and abs(amount) >= Decimal("1000"):
            formatted = _abbreviate_number(amount, decimals=1)
        else:
            pattern = f"{{:,.{decs}f}}" if self.group else f"{{:.{decs}f}}"
            formatted = pattern.format(amount)
        formatted = _apply_number_format(formatted, self.number_format)
        return f"{formatted} {policy.currency_symbol}" if include_symbol and policy.currency_symbol else formatted

    def format_quantity(self, value: Any, *, decimals: int = 2, trim: bool = True) -> str:
        num = decimal_value(value)
        q = _quantum(decimals)
        if abs(num) < q / Decimal("2"):
            num = Decimal("0")
        num = num.quantize(q, rounding=ROUND_HALF_UP)
        pattern = f"{{:,.{decimals}f}}" if self.group else f"{{:.{decimals}f}}"
        formatted = pattern.format(num)
        if trim and "." in formatted:
            formatted = formatted.rstrip("0").rstrip(".")
        return _apply_number_format(formatted or "0", self.number_format)

    def format_number(self, value: Any, *, decimals: int = 2, trim: bool = True) -> str:
        return self.format_quantity(value, decimals=decimals, trim=trim)

    def format_for_key(self, key: str, value: Any) -> str:
        k = str(key or "").lower()
        if k in MONEY_KEYS or any(token in k for token in ("price", "amount", "total", "balance", "debit", "credit", "cost")):
            return self.format_money(value)
        if k in QUANTITY_KEYS or any(token in k for token in ("qty", "quantity")):
            return self.format_quantity(value)
        return self.format_number(value)


def policy_for(payload: Mapping[str, Any] | None = None, currency_code: Any = None) -> MoneyDisplayPolicy:
    return MoneyDisplayPolicy.from_settings(currency_code=currency_code, payload=payload)


def format_money(value: Any, currency_code: Any = None, *, decimals: int | None = None, include_symbol: bool = True, payload: Mapping[str, Any] | None = None) -> str:
    return policy_for(payload=payload, currency_code=currency_code).format_money(value, decimals=decimals, include_symbol=include_symbol)


def format_quantity(value: Any, *, decimals: int = 2, trim: bool = True, payload: Mapping[str, Any] | None = None) -> str:
    return policy_for(payload=payload).format_quantity(value, decimals=decimals, trim=trim)


def format_number(value: Any, *, decimals: int = 2, trim: bool = True, payload: Mapping[str, Any] | None = None) -> str:
    return policy_for(payload=payload).format_number(value, decimals=decimals, trim=trim)
